DROP TABLE MENU_T;
CREATE TABLE MENU_T(
    MENU_NO NUMBER NOT NULL,
    BOB VARCHAR2(50 BYTE),
    GOOK VARCHAR2(50 BYTE),
    BANCHAN1 VARCHAR2(50 BYTE),
    BANCHAN2 VARCHAR2(50 BYTE)
);

DROP SEQUENCE MENU_SEQ;
CREATE SEQUENCE MENU_SEQ NOCACHE;

insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (1, 'Plymouth', 'Prowler', 'Rupiah', 'Purple');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (2, 'Chevrolet', 'Tahoe', 'Euro', 'Orange');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (3, 'Ford', 'E350', 'Rupiah', 'Purple');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (4, 'GMC', '3500 Club Coupe', 'Hryvnia', 'Pink');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (5, 'Honda', 'Passport', 'Yuan Renminbi', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (6, 'Buick', 'Park Avenue', 'Euro', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (7, 'Geo', 'Prizm', 'Dollar', 'Aquamarine');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (8, 'Pontiac', 'Firebird', 'Yuan Renminbi', 'Yellow');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (9, 'Pontiac', 'Sunbird', 'Yuan Renminbi', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (10, 'Aston Martin', 'V8 Vantage', 'Pound', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (11, 'Ferrari', '612 Scaglietti', 'Yuan Renminbi', 'Aquamarine');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (12, 'Toyota', 'T100 Xtra', 'Dinar', 'Orange');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (13, 'Ford', 'Taurus X', 'Yuan Renminbi', 'Puce');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (14, 'Mitsubishi', 'Pajero', 'Yuan Renminbi', 'Purple');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (15, 'Lotus', 'Elise', 'Yuan Renminbi', 'Yellow');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (16, 'Buick', 'LaCrosse', 'Dinar', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (17, 'Geo', 'Storm', 'Baht', 'Aquamarine');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (18, 'Ford', 'F-Series', 'Hryvnia', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (19, 'Honda', 'Odyssey', 'Rand', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (20, 'BMW', 'Z8', 'Franc', 'Red');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (21, 'Rolls-Royce', 'Ghost', 'Yuan Renminbi', 'Red');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (22, 'Volkswagen', 'New Beetle', 'Rupiah', 'Maroon');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (23, 'Chevrolet', 'Caprice Classic', 'Ruble', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (24, 'Mazda', 'MX-5', 'Zloty', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (25, 'Volvo', 'V70', 'Euro', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (26, 'Subaru', 'Forester', 'Dollar', 'Green');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (27, 'Honda', 'S2000', 'Yuan Renminbi', 'Mauv');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (28, 'Chevrolet', 'Sportvan G20', 'Rand', 'Yellow');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (29, 'Chevrolet', 'Beretta', 'Euro', 'Maroon');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (30, 'Chevrolet', 'Express 3500', 'Yuan Renminbi', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (31, 'Ford', 'F-Series', 'Yuan Renminbi', 'Teal');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (32, 'Plymouth', 'Neon', 'Real', 'Green');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (33, 'Hummer', 'H1', 'Yuan Renminbi', 'Green');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (34, 'Chevrolet', 'Blazer', 'Zloty', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (35, 'Ford', 'Focus', 'Peso', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (36, 'Ford', 'Escape', 'Koruna', 'Aquamarine');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (37, 'Volkswagen', 'Tiguan', 'Euro', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (38, 'Isuzu', 'i-370', 'Krona', 'Teal');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (39, 'Dodge', 'Ram 50', 'Won', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (40, 'Land Rover', 'Discovery', 'Euro', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (41, 'Honda', 'Accord', 'Peso', 'Yellow');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (42, 'Mitsubishi', 'Diamante', 'Yuan Renminbi', 'Red');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (43, 'Lincoln', 'Town Car', 'Zloty', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (44, 'Audi', 'A4', 'Franc', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (45, 'Chevrolet', 'Express 2500', 'Yuan Renminbi', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (46, 'Chrysler', '300M', 'Pound', 'Aquamarine');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (47, 'Ford', 'Econoline E350', 'Zloty', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (48, 'Nissan', 'Sentra', 'Yuan Renminbi', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (49, 'Ford', 'F-Series', 'Euro', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (50, 'Chevrolet', 'Suburban 1500', 'Euro', 'Green');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (51, 'Cadillac', 'DTS', 'Yuan Renminbi', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (52, 'Subaru', 'Legacy', 'Ruble', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (53, 'Lincoln', 'MKX', 'Rupiah', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (54, 'Kia', 'Spectra', 'Yuan Renminbi', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (55, 'Volvo', 'V70', 'Rupee', 'Aquamarine');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (56, 'GMC', 'Savana 2500', 'Yuan Renminbi', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (57, 'Oldsmobile', 'Cutlass Supreme', 'Yuan Renminbi', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (58, 'Mazda', 'Protege', 'Euro', 'Khaki');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (59, 'Nissan', 'Pathfinder', 'Lev', 'Orange');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (60, 'Audi', 'A6', 'Peso', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (61, 'Maybach', '57', 'Hryvnia', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (62, 'Dodge', 'Stratus', 'Yuan Renminbi', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (63, 'Chevrolet', '1500', 'Dong', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (64, 'Ford', 'F250', 'Rupiah', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (65, 'GMC', 'Sierra', 'Zloty', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (66, 'Land Rover', 'Range Rover', 'Marka', 'Yellow');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (67, 'Hyundai', 'Elantra', 'Peso', 'Khaki');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (68, 'Chrysler', 'Prowler', 'Dinar', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (69, 'Mercedes-Benz', 'SLS-Class', 'Peso', 'Puce');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (70, 'Mazda', '929', 'Rupiah', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (71, 'Chevrolet', 'Silverado 2500', 'Dollar', 'Green');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (72, 'Dodge', 'Grand Caravan', 'Yuan Renminbi', 'Red');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (73, 'Mazda', 'MX-6', 'Hryvnia', 'Purple');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (74, 'Mazda', '323', 'Yuan Renminbi', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (75, 'Jeep', 'Comanche', 'Marka', 'Maroon');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (76, 'Cadillac', 'Catera', 'Kwacha', 'Teal');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (77, 'Lexus', 'LS', 'Rial', 'Yellow');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (78, 'Mitsubishi', 'Galant', 'Yuan Renminbi', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (79, 'BMW', '5 Series', 'Peso', 'Khaki');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (80, 'Jaguar', 'XJ', 'Rupiah', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (81, 'Saab', '9-5', 'Dram', 'Fuscia');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (82, 'Subaru', 'Forester', 'Euro', 'Pink');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (83, 'Mercedes-Benz', 'S-Class', 'Hryvnia', 'Fuscia');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (84, 'Lincoln', 'MKS', 'Zloty', 'Maroon');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (85, 'GMC', 'Yukon XL 1500', 'Euro', 'Fuscia');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (86, 'Ford', 'F-Series Super Duty', 'Dirham', 'Pink');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (87, 'Chevrolet', 'Silverado', 'Ruble', 'Red');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (88, 'BMW', 'Z4 M Roadster', 'Pound', 'Orange');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (89, 'Volvo', 'S60', 'Euro', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (90, 'Buick', 'Century', 'Hryvnia', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (91, 'Mitsubishi', 'Raider', 'Dollar', 'Orange');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (92, 'Plymouth', 'Grand Voyager', 'Peso', 'Khaki');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (93, 'Dodge', 'Avenger', 'Taka', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (94, 'Ford', 'F350', 'Dollar', 'Puce');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (95, 'Hummer', 'H1', 'Peso', 'Red');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (96, 'Nissan', 'Versa', 'Zloty', 'Teal');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (97, 'Dodge', 'Ram 2500', 'Peso', 'Orange');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (98, 'Kia', 'Sportage', 'Dollar', 'Yellow');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (99, 'Chevrolet', 'G-Series G20', 'Dollar', 'Mauv');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (100, 'Mercedes-Benz', 'CL-Class', 'Ruble', 'Mauv');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (101, 'Dodge', 'Spirit', 'Yuan Renminbi', 'Maroon');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (102, 'GMC', 'Envoy XL', 'Yuan Renminbi', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (103, 'Kia', 'Sorento', 'Marka', 'Pink');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (104, 'Land Rover', 'Discovery', 'Dram', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (105, 'Oldsmobile', 'Aurora', 'Peso', 'Green');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (106, 'Volvo', 'S60', 'Yuan Renminbi', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (107, 'Isuzu', 'Rodeo', 'Krona', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (108, 'Subaru', 'Legacy', 'Ruble', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (109, 'Jeep', 'Grand Cherokee', 'Krona', 'Purple');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (110, 'Chevrolet', 'Venture', 'Rupiah', 'Red');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (111, 'Chevrolet', '3500', 'Peso', 'Pink');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (112, 'Pontiac', 'GTO', 'Zloty', 'Green');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (113, 'Ford', 'Mustang', 'Pound', 'Pink');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (114, 'GMC', 'Sonoma Club Coupe', 'Yuan Renminbi', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (115, 'Chevrolet', 'Silverado 1500', 'Krona', 'Purple');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (116, 'Dodge', 'Caravan', 'Dollar', 'Indigo');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (117, 'Toyota', 'Tundra', 'Rupiah', 'Fuscia');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (118, 'Hyundai', 'Elantra', 'Lempira', 'Puce');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (119, 'Chevrolet', 'S10 Blazer', 'Euro', 'Puce');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (120, 'Dodge', 'Stratus', 'Ruble', 'Purple');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (121, 'Dodge', 'Grand Caravan', 'Euro', 'Teal');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (122, 'Acura', 'TSX', 'Peso', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (123, 'Nissan', 'Armada', 'Peso', 'Fuscia');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (124, 'Ford', 'Ranger', 'Baht', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (125, 'Dodge', 'Stratus', 'Peso', 'Maroon');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (126, 'Pontiac', 'Torrent', 'Koruna', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (127, 'Nissan', 'Altima', 'Ruble', 'Mauv');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (128, 'Mercury', 'Grand Marquis', 'Peso', 'Pink');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (129, 'Buick', 'Lucerne', 'Peso', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (130, 'Mazda', 'RX-8', 'Yuan Renminbi', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (131, 'Honda', 'CR-V', 'Peso', 'Puce');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (132, 'Scion', 'tC', 'Euro', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (133, 'Lincoln', 'Mark VII', 'Peso', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (134, 'Mercury', 'Grand Marquis', 'Dollar', 'Violet');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (135, 'Kia', 'Forte', 'Nakfa', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (136, 'Toyota', 'Highlander', 'Peso', 'Purple');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (137, 'Ford', 'F-Series', 'Koruna', 'Khaki');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (138, 'Lexus', 'LS', 'Peso', 'Fuscia');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (139, 'Volvo', 'S80', 'Ruble', 'Teal');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (140, 'BMW', '5 Series', 'Rupiah', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (141, 'Pontiac', 'Grand Am', 'Won', 'Yellow');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (142, 'Toyota', 'Tacoma Xtra', 'Hryvnia', 'Turquoise');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (143, 'Nissan', 'Sentra', 'Manat', 'Crimson');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (144, 'Toyota', 'RAV4', 'Real', 'Blue');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (145, 'Hyundai', 'Accent', 'Real', 'Goldenrod');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (146, 'Oldsmobile', 'Bravada', 'Peso', 'Maroon');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (147, 'Buick', 'Special', 'Peso', 'Teal');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (148, 'Chevrolet', 'Colorado', 'Sol', 'Purple');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (149, 'Dodge', 'Ram 3500', 'Yuan Renminbi', 'Yellow');
insert into MENU_T (MENU_NO, BOB, GOOK, BANCHAN1, BANCHAN2) values (150, 'Mercury', 'Grand Marquis', 'Koruna', 'Khaki');
COMMIT;


DROP SEQUENCE USER_SEQ;
CREATE SEQUENCE USER_SEQ NOCACHE;
DROP TABLE USER_T;

CREATE TABLE USER_T(
    USER_NO NUMBER NOT NULL,
    USER_EMAIL VARCHAR2(100 BYTE) NOT NULL UNIQUE,
    PW  VARCHAR2(64 BYTE),
    CONSTRAINT PK_USER PRIMARY KEY(USER_NO)
);
