DROP TABLE MENU_T;
CREATE TABLE MENU_T(
    MENU_NO NUMBER NOT NULL,
    BOB VARCHAR2(50 BYTE),
    GOOK VARCHAR2(50 BYTE),
    BANCHAN1 VARCHAR2(50 BYTE),
    BANCHAN2 VARCHAR2(50 BYTE)
);

DROP SEQUENCE MENU_SEQ;
CREATE SEQUENCE MENU_SEQ NOCACHE;
